### ISSUE TITLE
support running on local file system 

### ISSUE THREAD

**Issue by kiszk** [SparkTC/spark-bench#1]

**Comment by ssavvides** [comment]
previous versions of spark-bench in bitbucket had support for local file system which was dropped in favor of a local hdfs installation when spark-bench was shipped to github. you can take a look at the bin/config.sh file here https://bitbucket.org/lm0926/sparkbench

**Comment by lm4limin** [comment]
To run in local mode, simply change  the following variables in bin/env.sh : DATA_HDFS="file:///home/`whoami`/SparkBench"
SPARK_MASTER=local[2]

**Comment by lm4limin** [comment]
SparkBench supports to run on local mode.
