### ISSUE TITLE
SQL gen_data.sh failure

### ISSUE THREAD

**Issue by abedad** [SparkTC/spark-bench#11]
running: `spark-bench-master/SQL/bin/gen_data.sh`
reports 

rm: cannot remove ‘/home/abed/SparkBench/sql/Input’: No such file or directory
./gen_data.sh: line 23: /home/abed/SparkBench/sql: No such file or directory
./gen_data.sh: line 24: /home/abed/SparkBench/sql/Input: No such file or directory
./gen_data.sh: line 31: /home/abed/SparkBench/dataset/BigDataGeneratorSuite/Table_datagen/e-com/output/*: No such file or directory
ssh: connect to host abed-virtualbox port 22: Connection refused
du: cannot access ‘/home/abed/SparkBench/sql/Input’: No such file or directory
./gen_data.sh: line 47: get_config_fields: command not found

**Comment by TopDstar** [comment]
yes, I have met the same problem: There is no /$SPARKBENCH/dataset directory

**Comment by lm4limin** [comment]
Fixed.
