### ISSUE TITLE
multi-submit-example.sh is missing from local builds

### ISSUE THREAD

**Issue by pjfanning** [SparkTC/spark-bench#115]
I followed the instructions in README.md to create spark-bench from sources but the `multi-submit-example.sh` was missing.
It does appear in the release tgz files.

**Comment by ecurtin** [comment]
Oh no! I thought I touched that up. Thanks for the catch! Fixing now

**Comment by pjfanning** [comment]
I also noticed that https://github.com/SparkTC/spark-bench/blob/master/readme.md has a number of references to your `ecurtin` fork. Should they be changed to refer to https://github.com/SparkTC/spark-bench instead?

**Comment by ecurtin** [comment]
Yep, you're right about the links! Fixed the references to multi-submit (it was deprecated awhile ago, too out of date) and the old links to ecurtin/spark-bench. Also updated instructions on setting environment variables as there's actually two methods!

**Comment by ecurtin** [comment]
Just patched this with #116. Thanks for your attention to detail! I'm gonna close this issue as fixed but lemme know if you catch anything else :)
