### ISSUE TITLE
Producing measurements like those in the paper?

### ISSUE THREAD

**Issue by msifalakis** [SparkTC/spark-bench#12]
I ve played a bit around with the tests that you have but I cannot find anywhere a log that would be giving me figures for the type of measurements you have in the paper (CPU utilisation, Cache utilisation, Disk IO and network IO).
Which part of the code/scripts generates such reports ?
tia
m.

**Comment by lm4limin** [comment]
We use ganglia to collect resource utilization information. http://ganglia.info/
