### ISSUE TITLE
Do we have a list of "all the workloads" we have now?

### ISSUE THREAD

**Issue by xiandong79** [SparkTC/spark-bench#124]
Do we have a list of "all the workloads" we have for "new spark-bench" now?

like we had in legacy spark-bench?

```
Machine Learning Workloads:

Logistic Regression
Support Vector Machine
Matrix Factorization
Graph Computation Workloads:

PageRank
SVD++
Triangle Count
SQL Workloads:

Hive
RDD Relation
```

**Comment by ecurtin** [comment]
Yep! It's on the documentation site: https://sparktc.github.io/spark-bench/workloads/

You can also see what's on the roadmap in Github issues, or more easily by installing the public version of Zenhub which sits on top of Github issues and creates an Agile board.

**Comment by ecurtin** [comment]
I'm gonna close this issue for now, feel free to reopen it or open a new one if you have more questions :)
