### ISSUE TITLE
can not open "https://github.com/Spark-TC/spark-bench/releases/latest"

### ISSUE THREAD

**Issue by gongshijun** [SparkTC/spark-bench#129]

**Comment by ecurtin** [comment]
Yeah, should be `SparkTC` not `Spark-TC`. Like: <https://github.com/SparkTC/spark-bench/releases/latest>
Where did you see the incorrect URL in the documentation?

**Comment by ecurtin** [comment]
Fixed with [commit 53a59ae](https://github.com/SparkTC/spark-bench/commit/53a59aeb570b54d4620d062cd813f3c32de4015d). Thanks for the good catch @gongshijun
