### ISSUE TITLE
Support ORC file format

### ISSUE THREAD

**Issue by naegelejd** [SparkTC/spark-bench#132]
ORC is a Spark built-in Data Source file format, as specified [here](https://spark.apache.org/docs/latest/sql-programming-guide.html#manually-specifying-options).

Adding ORC support to spark-bench might be as easy as adding a new `case` to each `match` statement that checks for Parquet (e.g. in utils/SparkFuncs `load` and `writeToDisk`).

**Comment by ecurtin** [comment]
Absolutely 100% agree that this needs to happen! 

Like you said, it should pretty much just be adding cases to the match statements in those functions (and adding tests!). I might be able to get around to this soon (working on #117 at the moment) but I'm also super open to contributions if you're interested in contributing yourself. Lemme know what you think!

**Comment by ecurtin** [comment]
Hi @naegelejd I just pushed a commit that adds ORC, JSON, and Avro support! It's running through TravisCI right now and a new distribution should be in Github releases in ~15 minutes.

**Comment by naegelejd** [comment]
Excellent, thank you!

**Comment by ecurtin** [comment]
Sure thing! Please let me know through an issue if you encounter any problems!
