### ISSUE TITLE
Where does report save at? #HELP_WANTED 

### ISSUE THREAD

**Issue by akasaki** [SparkTC/spark-bench#133]
In the previous version, I can view the result in the report folder. How about this new version? I accidentally closed the terminal window and didn't see the result. Should I run it again or I can find the report somewhere?

Thanks a lot.

### Spark Bench Version on Your Cluster

spark-bench_2.1.1_0.2.2-RELEASE_55

### Spark Version on Your Cluster

Spark 2.1.1.2.6.1.0-129

### Scala Version on Your Cluster
Scala version 2.11.8

**Comment by ecurtin** [comment]
Hi @akasaki, thanks for using Spark-Bench!

The output can go anywhere you want it to go! You can set a location using the `benchmark-output` for each of your workload suites. Using this, you can have your results output to the console by using `benchmark-output = "console"`, or to a file in local storage (not recommended), HDFS (recommended!), or any object storage that your cluster is set up to use such as S3. `benchmark-output = "hdfs:///tmp/my-amazing-spark-bench-results.csv"` Currently you can output your results as a CSV or as Parquet, support for more formats is in the works :)

**Comment by akasaki** [comment]
Thank you so much @ecurtin. I got it! For some reason, I couldn't save it to local disk, but not a big deal. HDFS is fine.

**Comment by ecurtin** [comment]
Sweet! Yeah, specifying a local disk path on a cluster can be complicated depending on your setup because it'll get written to the local disk of whatever node happens to be doing that particular task, not necessarily to the local disk of the filesystem. That's just a Spark thing, not a Spark-Bench thing.

Anyway, glad it worked for you!
