### ISSUE TITLE
Documentation for adding new workloads to the codebase is out of date

### ISSUE THREAD

**Issue by ecurtin** [SparkTC/spark-bench#136]
This page contains documentation that is out of date: https://sparktc.github.io/spark-bench/developers-guide/adding-new-workloads/

**Comment by akasaki** [comment]
Hi @ecurtin, I just saw this issue. Is the documentation updated? I am starting working on adding new workloads.

**Comment by ecurtin** [comment]
Hey @akasaki! I have not gotten around to fixing this quite yet as other stuff (#141 which has a PR now! and #83 which is about halfway done) have been higher priority, but I will get to it ASAP. If you install the free ZenHub plugin for your browser you can see the Agile board view of our issues :) Updating this documentation is very high priority but it's still in the backlog at the moment.

In the meantime, you can take a look at the data generation workloads and other workloads in [this directory](https://github.com/SparkTC/spark-bench/tree/master/cli/src/main/scala/com/ibm/sparktc/sparkbench) as a guide. Some of these are more complex than others. Basically everything inherits from [Workload](https://github.com/SparkTC/spark-bench/blob/master/cli/src/main/scala/com/ibm/sparktc/sparkbench/workload/Workload.scala) and WorkloadDefaults. New workloads in the codebase get tied into the existing config file marshalling system in [this method.](https://github.com/SparkTC/spark-bench/blob/master/cli/src/main/scala/com/ibm/sparktc/sparkbench/workload/ConfigCreator.scala#L30)

Let me know if you have any specific questions! I'm happy to help!

**Comment by ecurtin** [comment]
@akasaki Just merged the new documentation! I'd appreciate your feedback if you have any!
