### ISSUE TITLE
Update Graph Generator example to use smaller parameters

### ISSUE THREAD

**Issue by ecurtin** [SparkTC/spark-bench#139]
As noted in the discussion for #137, the example parameters in the documentation for the Graph Data Generator require beefier memory settings than the default. 

Change the parameters in the example to something much smaller and more default and local-environment friendly.

**Comment by Aalnafessah** [comment]
Thanks @ecurtin for your active support.

Using Scala , there is a way to add some delay same as the following : 
<img width="686" alt="screen shot 2018-01-10 at 8 25 51 pm" src="https://user-images.githubusercontent.com/30182419/34793884-c239e310-f644-11e7-93c5-c924d09c8b44.png">

What i need is to add same function inside code to be between jobs to examine spark performance. Where can i find the code that submit this job. For example these jobs:  
![image](https://user-images.githubusercontent.com/30182419/34794037-398a29fc-f645-11e7-8756-c38691f2ea07.png)
