### ISSUE TITLE
Submit parameters of workload in .conf file 

### ISSUE THREAD

**Issue by Aalnafessah** [SparkTC/spark-bench#144]
### Spark-Bench Version
spark-bench-launch-2.1.1_0.2.2-RELEASE

### Spark Version on Your Cluster
Spark.2.2.1

### Scala Version on Your Spark Cluster

Scala version 2.11.8
Spark Cluster: Spark Standalone ( 1 master and 2 slaves).
### Your Exact Configuration File (with system details anonymized)
```
<!--
spark-bench = {
  spark-submit-config = [{
    spark-args = {
      master = "spark://XXXXXXXXX:7077"
    }
    workload-suites = [
    {
      descr = "*** KMeans data gen *******"
      benchmark-output = "console"
      workloads = [
        {
        name = "data-generation-kmeans"
        rows = 10000000
        cols = 24
        output = "/tmp/kmeans-data2GBV1.csv" 
        k = 4500
        scaling = 1.6
        parititions = 10
        }
      ]
    }
    ]
  }]
}

 -->
```

### Description of Problem, Any Other Info
I am working on analysing Spark performance with a combination of different parameters ( rows, cols , K, scaling and partitions) of KMeans workload. The total number of possible combination of these parameters is around 40 experiments. Is it possible to pass these parameters of config file of SparkBench as arguments ?

**Comment by ecurtin** [comment]
There's two ways to accomplish this, and really the second is a shortcut of the first.

The first way is to create multiple workloads:

```
spark-bench = {
  spark-submit-config = [{
    spark-args = {
      master = "spark://XXXXXXXXX:7077"
    }
    workload-suites = [
    {
      descr = "*** KMeans data gen *******"
      benchmark-output = "console"
      workloads = [
        {
        name = "data-generation-kmeans"
        rows = 10
        cols = 2
        output = "hdfs:///tmp/dataset-with-10-rows.csv" 
        k = 4500
        scaling = 1.6
        parititions = 10
        },
        {
        name = "data-generation-kmeans"
        rows = 100
        cols = 2
        output = "hdfs:///tmp/dataset-with-100-rows.csv" 
        k = 4500
        scaling = 1.6
        parititions = 10
        }
      ]
    }
    ]
  }]
}
```
The second way you can do this is by using a shortcut feature in Spark-Bench that will create the permutations for you under the hood.

Here's an example using fake numbers just for illustration:

```
spark-bench = {
  spark-submit-config = [{
    spark-args = {
      master = "spark://XXXXXXXXX:7077"
    }
    workload-suites = [
    {
      descr = "*** KMeans data gen *******"
      benchmark-output = "hdfs://results-of-36-runs-of-kmeans.csv"
      workloads = [
        {
        name = "kmeans"
        rows = [10, 100, 1000]
        cols = [2, 4, 6, 8]
        k = [40, 50, 60]
        scaling = 1.6
        parititions = 10
        }
      ]
    }
    ]
  }]
}
```
This will produce 3 x 4 x 3 = 36 permutations of this kmeans workload under the hood and run them all.

**There is a caveat to this feature** which is that for workloads that write their results out (so any data generators or any workloads that specify `output`) if you try to use the permutations trick there'll be a bunch of workloads trying to write to the same file names and the first one to try to write to that file after its been created will fail, followed by all the others failing. In this case, at the moment, your best/only option is to create multiple workloads as in the first example.

**Comment by Aalnafessah** [comment]
Thanks for your valuable help @ecurtin . I will follow your recommendation. 

If I want to generate specific size of output data from the ` name = data-generation-kmeans`. For example, if i want to generate 64GB of output data from this KMeans data generator, what is the value of parameters (ex: row and cols) that i need to chose?

**Comment by ecurtin** [comment]
I don't have an exact formula. My advice would be to first fix the number of columns you want to generate and then play around with small dataset sizes to figure out a rough size-per-row given that many columns or size-per-hundred-rows given that many columns or something like that which you can use to calculate the dataset size necessary for 64GB worth of data.

If you do come up with some numbers, let me know because that would be valuable to add to the documentation!

**Comment by Aalnafessah** [comment]
@ecurtin 
I have run 3 KMeans data generation as shown in the following config file:
```
spark-bench = {
  spark-submit-config = [{
    spark-args = {
      master = "spark://picard03.doc.ic.ac.uk:7077"
    }
    workload-suites = [
    {
      descr = "*** KMeans data gen *******"
      benchmark-output = "console"
      workloads = [
        {
        name = "data-generation-kmeans"
        rows = 10000
        cols = 500
        output = "/scratch/kmeans-data-EmilyV1.csv"
        k = 4500
        scaling = 1.6
        parititions = 1
        }
        ,
        {
        name = "data-generation-kmeans"
        rows = 30000
        cols = 500
        output = "/scratch/kmeans-data-EmilyV2.csv"
        k = 4500
        scaling = 1.6
        parititions = 1
        }
        ,
        {
        name = "data-generation-kmeans"
        rows = 50000
        cols = 500
        output = "/scratch/kmeans-data-EmilyV3.csv"
        k = 4500
        scaling = 1.6
        parititions = 1
        }
      ]
    }
    ]
  }]
}

```

I have chosen a fixed number of columns which is 500 and also the other parameters (k, scaling and partitions) are same.  I have played with the number of rows as you suggested and i have chosen the number of row in the three workloads to be 10k, 30k and 50k respectively. The following data have been generated: 
1)       R1= Number of Rows = 10k        ==> generates 48.5MB
2)      R2= Number of Rows  = 30k      ==> generates 145.3MB
3)      R3= Number of Rows  = 50k      ==> generates 242.2MB

Therefore the ratio is `X` can be calculated as follow: `X=DataSize / R `. Here is `X` for every data:
1)     X1= 48.5MB / 10k = .00485        
2)    X2= 145.3MB / 30k  = .00485
3)    X3= 242.2MB / 50k  = .00485

Finally, To find out the number of Rows that you need to choose R:
```
R = DataSize / X
-------------------
```
 In my case, I want to generate data with size 64GB:
`R = 64000MB / .00485 
`R  = 13,195,876`

Now I am being able to generate data set of size 64GB by choosing number of columns  ( in my case 500 columns) and  calculating Ration X to find out the number of Rows

**Comment by ecurtin** [comment]
Thank you for all your research! I'm going to close this issue.
