### ISSUE TITLE
How to change configuration in legacy version

### ISSUE THREAD

**Issue by akasaki** [SparkTC/spark-bench#151]
### Spark-Bench Version
spark-bench-legacy 

### Spark Version on Your Cluster

Spark 2.1.1.2.6.1.0-129

### Scala Version on Your Spark Cluster
Scala 2.11.8

### Your Exact Configuration File (with system details anonymized)

Here is the default config.sh file. 

if [ -f "${bin}/../conf/env.sh" ]; then
  set -a
  . "${bin}/../conf/env.sh"
  set +a
fi

APP=LogisticRegression
APP_DIR=${DATA_HDFS}/${APP}
INPUT_HDFS=${DATA_HDFS}/${APP}/Input
OUTPUT_HDFS=${DATA_HDFS}/${APP}/Output

// Either stand alone or yarn cluster
APP_MASTER=${SPARK_MASTER}

set_gendata_opt
set_run_opt

function print_config(){
               get_config_values $1 $2 $3 $4 $5 $6
}

function get_config_fields(){
   local report_field=$(get_report_field_name)  
    echo -n "#${report_field},AppType,nExe,driverMem,exeMem,exeCore,nExample,nFeature,EPS,nPar,Intercepts,nIter,memoryFraction,STEP_SIZE,noise,lambda,miniBatch,sparseness,convergenceTol" 
     echo -en "\n"
                    
}
function get_config_values(){
      gen_report $1 $2 $3 $4 $5 $6
      echo -n ",${APP}-MLlibConfig,$nexe,$dmem,$emem,$ecore,${NUM_OF_EXAMPLES},${NUM_OF_FEATURES},${EPS},${NUM_OF_PARTITIONS},${INTERCEPTS},${MAX_ITERATION},${memoryFraction},${STEP_SIZE},$noise,${lambda},${miniBatch},${sparseness},${convergenceTol}" 
       echo -en "\n"
       return 0
}

### Description of Problem, Any Other Info

I am wondering if I can modified some config parameters such as spark.executor.memory, spark.shuffle.compression, etc. Where should I add and in what format?

Also is it possible to run the same workload with different settings as in the new version shown below?

conf = [
  {
    "spark.dynamicAllocation.enabled" = "false"
    "spark.shuffle.service.enabled" = "false"
  },
  {
    "spark.dynamicAllocation.enabled" = "true"
    "spark.shuffle.service.enabled" = "true"
  }
]

**Comment by ecurtin** [comment]
Hi @akasaki! 

So part of the motivation for the rewrite is that the legacy version _doesn't_ have any of the same infrastructure for changing configuration and easily generating multiple runs. It's all written in the bash that you've already started exploring. 

My best suggestion if you need workloads in the legacy version is to fork the legacy version and modify the bash as necessary to suit your individual case :(

**Comment by akasaki** [comment]
Hi @ecurtin, thank you for the reply.

I am still wondering how to modify the configurations and in which format. Is it possible to show my a simple example? What if I want to change "spark.shuffle.compression" to "false"? Where should I add the line to the config.sh? 

Thank you so much for taking time!

**Comment by akasaki** [comment]
Hi @ecurtin, never mind. I figured out. Something like "SPARK_SERIALIZER = org.apache.spark.serializer.KryoSerializer". I just want to double check with you if my understand is right. The parameter has to be capitalized and replace '.' to '_'. Is it right?

**Comment by ecurtin** [comment]
Hi @akasaki. There's a couple ways to change a configuration parameter like the serializer. What you're doing by setting a bash variable like that is overriding the variables in `spark-env.sh` in you Spark installation conf directory. That's a totally legit way of doing things! You can also dig into the bash in the legacy version a little bit and find where `spark-submit` is getting called. From there you can modify the actual call just like you'd do if you were calling spark-submit from the command line.

**Comment by akasaki** [comment]
Hello @ecurtin, I am trying to run multi-run.sh in the legacy version. But the following error was raised. 
ubuntu@xxxx:~/spark-bench-legacy/MatrixFactorization/bin$ ./multi-run.sh 
./multi-run.sh: 3: /home/ubuntu/spark-bench-legacy/MatrixFactorization/../bin/config.sh: Bad substitution
env.sh is missing

The env.sh file is located under Sparkbench_Home/workload/conf. Should I copy it to ./bin?

**Comment by ecurtin** [comment]
@akasaki You can certainly try that! 

I am unfamiliar with the details of the legacy version as I was not involved in its development, so unfortunately it's there as-is and I can't provide too much support :(

**Comment by akasaki** [comment]
@ecurtin, I see. It doesn't work with the env.sh file in ./bin. No worries. I can run all the workloads individually. Thank you so much for your support so far.
