### ISSUE TITLE
can't connect "https://oss.sonatype.org/content/groups/scala-tools/"

### ISSUE THREAD

**Issue by echoqu** [SparkTC/spark-bench#20]
in pom.xml : <url>https://oss.sonatype.org/content/groups/scala-tools/</url>
but  i can't connect "https://oss.sonatype.org/content/groups/scala-tools/",what should i do?

**Comment by RowlingLuo** [comment]
Have you solved the problem yet? I encountered this too. And I found that there is no scala-tools under this path "https://oss.sonatype.org/content/groups". and the alternative is "https://oss.sonatype.org/content/repositories/snapshots/", as the "http://scala-tools.org/" suggests. But there is no nlp under the path "https://oss.sonatype.org/content/groups/scala-tools/edu/jhu/" either. 

Any advice will be appreciated.
Thanks

**Comment by jthimer** [comment]
I finally did find a solution.

There is a Nexus repository manager at:  https://oss.sonatype.org/#welcome
Using the search there, one can see there are several versions of scala-tools including the one SparkBench requires.

To grab them, I replaced 

  https://oss.sonatype.org/content/groups/scala-tools/

with 

  https://oss.sonatype.org/service/local/repositories/central-sync/content/org/scala-tools/

in the two places in the main SparkBench pom.xml it appears.

It worked for me for a rebuild just now.   Thankfully, I backed up my ~/.m2 where I had the original scala-tools cached from long ago so my Spark Bench builds were never in danger --  but that doesn't help new-comers to this site!  But it does reinforce to me that that ~/.m2 is a treasure esp. when necessary cloud-ware simply goes AWOL at times.

----
P.S. I really do wish this benchmark suite had better continued support from the original authors.  The suite started out with such considerable promise but judging by how long many of these issues take to be finally addressed, it now has the appearance of an unwanted orphan.

**Comment by ecurtin** [comment]
Hi All, thank you for taking the time to submit an issue to spark-bench!

The project has recently gone through a major ground-up rewrite. While we're still working on porting all the workloads available in the legacy version, the new version offers a huge amount of flexibility and configurability that was not available in the old version. Check it out! I'd welcome your questions and feedback, and contributions are definitely welcome!

For now, I am going to close this issue as it's targeted at the legacy version.
