### ISSUE TITLE
spark-bench on a standalone cluster manager (not yarn)

### ISSUE THREAD

**Issue by MazenEzzeddine** [SparkTC/spark-bench#26]
Hi,

it it possible to deploy and execute spark-bench on a spark cluster with a standalone cluster manager? any hint please?

**Comment by pfxuan** [comment]
@MazenEzzeddine, spark-bench supports the standalone deploy mode for running spark benchmarks. You just need to specify `SPARK_MASTER` address in `conf/env.sh`:
```Bash
SPARK_MASTER=spark://${master}:7077
```

**Comment by MazenEzzeddine** [comment]
Excellent,  as I am running spark-bench on my own small cluster.

Thanks.
