### ISSUE TITLE
How to configure spark-bench so that I can run it in yarn cluster mode?

### ISSUE THREAD

**Issue by alphalzh** [SparkTC/spark-bench#27]
Thanks for the work in developing spark-bench.
I've got a question in use: in env.sh, there's a parameter "master". I've tried to set it to yarn, but it won't work and there are exceptions showing `Failed to connect to master yarn:7077`.

I just wonder how should I set the configuration file so that I can use yarn cluster mode to run it? Thanks in advance.

**Comment by pfxuan** [comment]
Which version of Spark were you running? To Spark 1.6 or later, you can set `SPARK_MASTER=yarn` in configuration file `env.sh`.

**Comment by alphalzh** [comment]
Thanks!
