### ISSUE TITLE
PageView Streaming Benchmark not working

### ISSUE THREAD

**Issue by shujamughal** [SparkTC/spark-bench#32]
Hi All,
I am trying to run this benchmark on a single node setup. but it is not running even I changed these two things in code.

1- in gen-data file. I changed the path of jar as follow

 JAR="${DIR}/target/StreamingApp-1.0.jar"

out in first terminal for data_gen is below

...
date purged on shuja
sh -c  /home/shuja/Desktop/data/spark-1.6.2-bin-hadoop2.6/bin/spark-submit --class src.main.scala.PageViewGenerator --master spark://shuja:7077   --conf spark.storage.memoryFraction=0.6 --conf spark.serializer=org.apache.spark.serializer.KryoSerializer --conf spark.rdd.compress=false --conf spark.io.compression.codec=lzf /home/shuja/Desktop/data/spark-bench-master/Streaming/target/StreamingApp-1.0.jar  44444 80000000 2>&1|tee /home/shuja/Desktop/data/spark-bench-master/bin/..//num/streaming_PageViewStream_genData_2016-08-30-12:04:18.dat
Listening on port: 44444

so it looks, data_gen part is working fine

2- in run. sh, I changed to localhost in following lines.

elif [ $subApp = "PageViewStream"  ];then
        OPTION="errorRatePerZipCode **localhost** 44444"
        #CLASS="org.apache.spark.examples.streaming.${subapp}"
        CLASS="src.main.scala.PageViewStream"

But the output of run is second terminal is

...
./bin/run.sh: line 100: get_config_fields: command not found

Could anyone help me out?
Thanks
Shuja

**Comment by mmozum** [comment]
Hi Shuja,

Seems copying this function from other config.sh in parallel workloads fixes this. But be sure to copy get_values and print_values too. The print_values existing in config.sh does not work properly. Once you copy all three (remove existing print function) then you will see this error gone and also some data is output into the reports.dat under num folder.

Bests,
-Monir

**Comment by ecurtin** [comment]
Thanks for submitting an issue to spark-bench!

Spark-bench has recently gone through a major rewrite, and it looks like this issue is targeted towards the legacy version. 

If you'd like to reopen this issue for examination against the legacy branch feel free, but I am going to close this for now due to inactivity.
