### ISSUE TITLE
Do we have a "Load Generator" which simulates job-submits in a day/period??

### ISSUE THREAD

**Issue by xiandong79** [SparkTC/spark-bench#55]
Do we have a "Load Generator" plan which simulates job-submits in a day/period??

maybe it can simulate that multiple users submit jobs in a ? Possion distribution ? in 2 hours?

**Comment by ecurtin** [comment]
Hi @xiandong79!

This is not something that's currently implemented but is definitely on the roadmap!

Probably the first step will be implementing a Poisson distribution parameter for the Sleep workload.

Currently you can approximate this with features already in spark-bench. (Note to self, this would be helpful to add to the docs) 

Start by building a few workload suites to run in parallel with the workloads within each suite running serially. Each workload suite would represent one user. Between each of the workloads, insert a [Sleep workload](https://github.com/SparkTC/spark-bench/blob/master/docs/workloads-and-parameters.md#sleep) and tune accordingly.

**Comment by xiandong79** [comment]
I found similar repo- https://github.com/IBM/SparkMultiuserBenchmark which is also designed to measure resource manager performance for Multi-User & Sync/Unsync batch/interactive Spark workloads.  


I think the "User case" of SparkMultiuserBenchmark is what we researchers want.
